version: "3.2"
services:
  php:
    build: './config/php/'
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html/
    env_file: src/.env
  nginx:
    build: './config/nginx/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
  mysql:
    build: './config/mysql/'
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports: 
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8181:8080"
    networks:
      - backend
networks:
  frontend:
  backend: